MujocoPlugins:
  - type: mujoco_ros_control/MujocoRosControlPlugin
    hardware:
      type: mujoco_ros_control/DefaultRobotHWSim
      control_period: 0.001
      robot_namespace: "rrbot"

# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  
  
# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint1
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint2
  pid: {p: 100.0, i: 0.01, d: 10.0}
